### ISSUE TITLE
Adjust theme for selection and tab navigation

### ISSUE THREAD

**Issue by T3sT3ro** [uetchy/math-api#290]
https://github.com/uetchy/math-api/blob/f2cb768241cf034b20aa6d1761d49d0d254f1645/index.html

Add the following to styles, otherwise the selection and focus is hardly visible:

```css
:root {
    --accent-triadic: #FF5E05;
}

.input-field::selection {
    background: var(--accent-triadic);
}

*:focus-visible {
    outline: .25em solid var(--accent-triadic);
    outline-offset: .25em;
}
```
